USE [master]
GO

CREATE SERVER AUDIT [DDL-Audit]
TO FILE 
(	FILEPATH = N'<path>'
	,MAXSIZE = 256 MB
	,MAX_FILES = 2
	,RESERVE_DISK_SPACE = OFF
)
WITH
(	QUEUE_DELAY = 1000
	,ON_FAILURE = CONTINUE
)
GO

--AUDIT NEEDS TO BE ENABLED

USE [master]
GO

CREATE SERVER AUDIT SPECIFICATION [DDLAuditSpecification]
FOR SERVER AUDIT [DDL-Audit]
ADD (DATABASE_OBJECT_CHANGE_GROUP),
ADD (DATABASE_CHANGE_GROUP),
ADD (SCHEMA_OBJECT_CHANGE_GROUP)
GO


--AUDIT SPECIFICATION NEED TO BE ENABLED